#!/usr/bin/env php
<?php

require __DIR__ . '/tests/bootstrap.php';

$tests = [];

foreach (glob(__DIR__ . '/tests/*Test.php') ?: [] as $testFile) {
    $loaded = require $testFile;

    if (is_array($loaded)) {
        $tests = array_merge($tests, $loaded);
    }
}

exit(lh_run_tests($tests));
